version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media 
      - static_volume:/app/staticfiles 
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  media_volume: 
  static_volume:  
