# Generated by Django 4.2.3 on 2025-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Blog category (e.g., Fashion, Sustainability)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="A short summary of the blog post", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured posts will be displayed on the home page",
            ),
        ),
    ]
